### ISSUE TITLE
Bug: `nvim +"autocmd VimEnter * qa!"` would be stuck.

### ISSUE THREAD

**Issue by LumaKernel** [vim-denops/denops.vim#136]
# Env

- vim/nvim: `nvim`
- vim/nvim --version: `NVIM v0.5.0`
- platform: WSL2 Ubuntu20.04
- denops.vim version: from `v1.10.1` to latest ( `v2.0.0` )

# Repro

1. Just install `denops.vim`.

  ```vim
  " Install vim-plug
  " let &rtp .= ',' . expand('<sfile>:h')
  call plug#begin(expand('<sfile>:h/plugged'))
  Plug 'vim-denops/denops.vim'
  call plug#end()
  ```

2. `nvim +"autocmd VimEnter * qa!"`

# Expect

`nvim` finishes.

# Actual

`nvim` was stuck.

```
[denops] Server stopped (143). Restarting...
```

and I should stop this by hitting `CTRL-C`.

![image](https://user-images.githubusercontent.com/29811106/135086883-42527b5d-90db-4513-8db7-125b7b00aedf.png)

# More

I confirmed it's come from `call denops#server#start()`

**Comment by lambdalisue** [comment]
Could you try if `nvim +"autocmd VimEnter * ++nested qa!"` fix the behavior?

**Comment by LumaKernel** [comment]
Yes, it works. Thank you.
Can I close this issue?

**Comment by lambdalisue** [comment]
No. I'll fix the issue on Neovim while `vim +"autocmd VimEnter * ++nested qa!"` works.
