### ISSUE TITLE
Typo(?) in the README.md

### ISSUE THREAD

**Issue by Hayashi-Yudai** [vim-denops/denops.vim#142]
In the readme, `vim-denops/denops-helloworld.vim` is introduced as a test of installation. It instructs to type `:HelloDenops` command, but this gives an error `E492: Not an editor command: HelloDenops`.

Seeing the denops-helloworld.vim repository, `:DenopsHello` command is introduced, and it works well in my environment. Is the `:HelloDenops` command in the readme of this repository a typo of `:DenopsHello`?

### My Vim environment
- Ubuntu 20.04
- Vim 8.2.3459
- deno 1.14.2 (release, x86_64-unknown-linux-gnu)
- v8 9.4.146.16
- typescript 4.4.2

**Comment by lambdalisue** [comment]
Already fixed.
https://github.com/vim-denops/denops.vim/pull/140
