### ISSUE TITLE
Can't boot denops.vim in no internet connection environment.

### ISSUE THREAD

**Issue by io3432iooivzs** [vim-denops/denops.vim#187]
Hi.
I'm using denops.vim for skkeleton(Japanese input method plugin for vim).
It works fine in during to connect the internet.
But I tried to launch skkeleton in no internet connection environment, I've got a under error message and can't enable denops.vim.

[denops] Server stopped 3 times within 10000 millisec. Denops become disabled to avoid infinity restart loop.

denops needs the internet connection always?

My environment:
Debian 11
Vim 8.2 Included patches: 1-4103
Installed denops.vim and skkeleton via vim-plug

**Comment by Shougo** [comment]
Unfortunately, it is deno's feature.  It does not work without internet connection.

You should copy deno cache file like this from internet connected machine.

https://zenn.dev/kawarimidoll/articles/3f06083cb03b25

It should work.

**Comment by io3432iooivzs** [comment]
> You should copy deno cache file like this from internet connected machine.

Woks fine, thanks.
