### ISSUE TITLE
Failing to connect to denops server

### ISSUE THREAD

**Issue by lukelbd** [vim-denops/denops.vim#192]
Recently I keep getting `[denops] Failed to connect denops server: Failed to connect 127.0.0.1:port` error messages and autocomplete stops working. Here's the full message after `:let g:denops#debug = 1 | call denops#server#restart()`:

```log
[denops] Server spawned: ['deno', 'run', '-q', '--no-check', '--unstable', '-A', '/Users/ldavis/dotfiles/.vim
/plugged/denops.vim/denops/@denops-private/cli.ts', '--mode=vim']
[denops] DenopsStarted
[denops] Connecting to `127.0.0.1:53944`
[denops] Failed to connect denops server: Failed to connect `127.0.0.1:53944`
[denops] Server stopped: -1
[denops] DenopsStopped
```

I tried switching from deno 1.17.0 to the latest version 1.22.0 but this did nothing. I'm using macOS 12.4 (Monterey). I've also updated to the latest version of `denops.vim` with `:PlugUpdate` and the latest version of vim: 8.2.3901.

Anything else I can do to try to debug this? I tried manually running the command `deno run -q --no-check --unstable -A /Users/ldavis/dotfiles/.vim/plugged/denops.vim/denops/@denops-private/cli.ts --mode=vim` and it seems to work fine... for some reason vim is just unable to connect with `ch_open`... it's really strange.

**Comment by lukelbd** [comment]
Sorry I only use vim not neovim... not sure how to install denops in neovim?

I tried downgrading to vim 8.2.3582, and I tried commenting out all vim-plug lines except `Plug 'vim-denops/denops.vim'`, but these did not work.

**Comment by Shougo** [comment]
Hm.  The port may be blocked by security.  Can you check it in another machine or VM?

**Comment by Shougo** [comment]
I have tested ddc.vim with Vim latest version.  It works for me.

**Comment by Shougo** [comment]
> Sorry I only use vim not neovim... not sure how to install denops in neovim?

Please install neovim from source and use denops without extra config.

**Comment by lukelbd** [comment]
I didn't test in neovim but restarting my macbook solved the problem. Still not sure why it happened... but hopefully this thread will be useful for someone else.

**Comment by dwolfhub** [comment]
> restarting my macbook solved the problem
I had to do this as well after installing deno and plugins

**Comment by Shougo** [comment]
I think the port is used or blocked by other applications.

**Comment by stevematney** [comment]
> I think the port is used or blocked by other applications.

I'm experiencing this as well. I think @Shougo is correct that it's being blocked. The only thing that has solved it so far is rebooting. Here are the other things I've tried:

1. Restarting Vim
2. Changing networks
3. Turning network/wifi on and off again
4. Running `:call denops#server#restart()` — This fails every time on different ports
5. Manually running the denops server and using `:call denops#server#connect`
    Same issue:
    ```
    [denops] Failed to connect `127.0.0.1:32123`: Failed to connect `127.0.0.1:32123`
    ```
6. Manually running `ch_open` and then `ch_status` on  `127.0.0.1:32123` while the server runs.
    `ch_status` returns `fail`.

I'll continue investigating what's blocking this connection.

**Comment by lambdalisue** [comment]
> [denops] Failed to connect `127.0.0.1:32123`: Failed to connect `127.0.0.1:32123`


It seems you accidentally set `let g:denops_server_addr = '127.0.0.1:32123'`? That's for **shared server** feature so without using shared server, the connection will fail as expected.

**Comment by stevematney** [comment]
> It seems you accidentally set `let g:denops_server_addr = '127.0.0.1:32123'`? That's for **shared server** feature so without using shared server, the connection will fail as expected.

I forgot to mention! This was not accidental. I wanted a consistent IP for the denops server for debugging, so I set that IP and ran the server manually. **Then** I tried running the `connect` command with the same results.

So, to be clear, the server was running while I was doing this (and it could receive commands from other processes).

**Comment by stevematney** [comment]
One thing to note: other Vim plugins that use connections (like ALE with LSPs running) continue to work. I’ve been doing some investigating to try to derive why these work while denops does not, but I haven’t reached any conclusions yet.

**Comment by Shougo** [comment]
@stevematney What is your environment?
I think you should test it with other environment.

**Comment by stevematney** [comment]
> @stevematney What is your environment? I think you should test it with other environment.

@Shougo my work machine is a managed Macbook Pro with an Intel processor. I'm fairly certain it has something to do with the firewall that I can't modify or disable, and possibly some of the VPN integration stuff. I know there's not much I can do at the network level to isolate the issue. This is why I'd like to get to the bottom of why other plugins work and denops doesn't. If I can find that, maybe I can figure out how to keep denops running for me.

I also have been using denops and ddc on a personal M1 Macbook Pro, and haven't seen the same issue. It seems pretty clear that it has something to do with the setup on my other machine.

**Comment by Shougo** [comment]
Oh, OK.  So it seems VPN or security soft or the firewall blocks denops connection.
Unfortunately, we cannot fix the problem from denops side.

>  This is why I'd like to get to the bottom of why other plugins work and denops doesn't. If I can find that, maybe I can figure out how to keep denops running for me.

The other software is popular, but denops is not.  So they may block.  It is terrible.
You can request denops connection should not be blocked though.

**Comment by lambdalisue** [comment]
It seems more investigation is required so reopen it.

**Comment by lambdalisue** [comment]
I haven't heard related issue recently so close it. Please create a new one if you face similar issue.
