### ISSUE TITLE
Create denops.vim visual image which follows the taste of the Deno's cute one.

### ISSUE THREAD

**Issue by lambdalisue** [vim-denops/denops.vim#2]
Like the image below.

[![image](https://user-images.githubusercontent.com/546312/107720330-7d623780-6d1d-11eb-913d-fdb6df36b897.png)](https://deno.land/)

From https://deno.land/

**Comment by hashrock** [comment]
![denops-chara](https://user-images.githubusercontent.com/3132889/113470275-51e30a00-948f-11eb-81bb-812986d131d5.png)
This character was created during a deno-ja meetup.
The image license is MIT, and you are free to change the design of the characters.

**Comment by lambdalisue** [comment]
Thanks a lot! We'll use that image!

**Comment by hashrock** [comment]
The logo license is entrusted to the vim-denops organization. Users must comply with the terms and conditions set forth below.

https://github.com/vim-denops/denops-logos

Please contact a representative of vim-denops for licensing information, not me.

vim-denops organization members are allowed to reuse and modify the logo without limitation.
