### ISSUE TITLE
Out dated deno's dependency

### ISSUE THREAD

**Issue by hgigas** [vim-denops/denops.vim#204]
Starting neovim:
```
[denops] docker: TypeError: Import 'https://dev.jspm.io/react@16.13/index.js' failed: 500 Internal Server Error
[denops]     at https://deno.land/x/servest@v1.3.4/vendor/https/dev.jspm.io/react/index.js:4:32
```
- neovim config:
```
use {
  'vim-denops/denops.vim',
}
```
- neovim version: 0.8.0
- deno versión:
  deno 1.25.2 (release, x86_64-unknown-linux-gnu)
  v8 10.6.194.5
  typescript 4.7.4

Pull request https://github.com/vim-denops/denops.vim/pull/200 not working

**Comment by lambdalisue** [comment]
We don't use https://deno.land/x/servest. Probably this is an issue of some denops plugin (I don't know which)

**Comment by Shougo** [comment]
You should create the minimal vimrc.

**Comment by Shougo** [comment]
https://dev.jspm.io/react@16.13/index.js seems does not work.  But it is *not* denops problem.

**Comment by hgigas** [comment]
Thanks for the quick reply. I don't know what is happening, i can't get it to work.

Greetings

**Comment by lambdalisue** [comment]
https://github.com/search?q=denops+https%3A%2F%2Fdeno.land%2Fx%2Fservest%40v1.3.4&type=code

Maybe you are using denops-docker? Anyway, it's not an issue of denops itself so closing it.

**Comment by hgigas** [comment]
Thank you very much. Yes, I'm using denops-docker. I'm sorry...
