### ISSUE TITLE
Denops crashing when launching vim

### ISSUE THREAD

**Issue by amadeus** [vim-denops/denops.vim#240]
When I launch vim I see this error:

<img width="932" alt="CleanShot 2023-01-11 at 12 52 51@2x" src="https://user-images.githubusercontent.com/83376/211915501-2b548576-ac2d-470e-b3e8-d2654fa89c15.png">

It looks like this [line](https://github.com/vim-denops/denops.vim/blob/ccf70548264620d15b9ec0f4e4d0cc46d64de023/autoload/denops/server.vim#L117) needs to become `--no-check`?

**Comment by Shougo** [comment]
I think your deno's version is too old.
Please upgrade your deno.

**Comment by Shougo** [comment]
Please see the comment.

https://github.com/vim-denops/denops.vim/pull/207#issuecomment-1356660539

**Comment by amadeus** [comment]
Ahh icic, yup that was probably it, thanks!

Perhaps there should be a deno version check on launch and an error message saying to update if we aren't running the correct version

**Comment by Shougo** [comment]
> Perhaps there should be a deno version check on launch and an error message saying to update if we aren't running the correct version

It seems hard.  Because it affects the performance.

**Comment by lambdalisue** [comment]
We can use `checkhealth` command in Neovim or Vim with [rhysd/vim-healthcheck](https://github.com/rhysd/vim-healthcheck). It produces the following messages so users can find the reason.

```
denops: health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.28.0`
  - INFO: Detected Deno version: `1.26.2`
  - ERROR: Unsupported Deno version is detected. You need to upgrade it to `1.28.0` or later.
  - INFO: Supported Neovim version: `0.8.0`
  - INFO: Detected Neovim version: `0.8.2`
  - OK: Neovim version check: passed
  - INFO: Denops status: `stopped`
  - ERROR: Denops is stopped. Execute `:message` command to find reasons.

```

**Comment by lambdalisue** [comment]
Above are on Wiki now
https://github.com/vim-denops/denops.vim/wiki#how-to-find-the-reason-why-denopsvim-does-not-work
