### ISSUE TITLE
vim9 dependency reason

### ISSUE THREAD

**Issue by sankl** [vim-denops/denops.vim#247]
Hello,
I came accross this project and it looks really interesting, due to relying on single-executable deno runtime approach. This would suggest the whole ecosystem is based on stable, reliable, and simple platform. What I realized is required vim version has been switched from 8 to `9.0.0472` which is not that ubiquitous nor that simple managed single executable as deno. The question is what was the reason to switch and where I'll be hit hard if I keep using vim 8 with forsing `g:denops_disable_version_check`?
Thank you!

**Comment by Shougo** [comment]
https://github.com/vim-denops/denops.vim/commit/fe250c6270d9fa81c1b9d64e31b080908a48fba0
https://github.com/vim/vim/commit/a4abe514ecd9b7a038feed89f48476809775c80f

I have checked the commit and I don't see the any technical reason.

> Support most latest version on homebrew

Hm.  From the commit message, @lambdalisue wants to use the latest version of Vim/neovim.
The latest Vim/neovim has more features and stable than older version.

> The question is what was the reason to switch and where I'll be hit hard if I keep using vim 8 with forsing g:denops_disable_version_check?

You can disable the check, but it is not supported.

**Comment by sankl** [comment]
Hi, thank you for the response! Vim 9 is not backward compatible with Vim 8, and is rarely available on the systems. Forcing plugin dev people updating to meet Vim 9 minimum requirement will bring more Vim 9 dependent features to denops plugins and so leave most of Vim users out of the ecosystem as updating VIm is not always possible/desirable. Did not it make some kind of departure from the project goals of providing common ground for Vim/Neovim? I'm just trying to have as little tweaks around the systems as possible, and Vim 9 is not available on any of them. Thanks again!

**Comment by Shougo** [comment]
You can build the latest Vim/neovim.
I think `denops.vim` does not use Vim 9 script yet.  Because it does not support in neovim.
To force the latest version, it has the advantage.
Denops plugins can use more new features except Vim9 script.

**Comment by sankl** [comment]
Ok, I see, as long as `vim-denops` itself is running with Vim using it, there should be no apparent Vim-version related problems brought by `vim-denops` plugins, as they are deno-based. Awesome.

**Comment by sankl** [comment]
Closing.
