### ISSUE TITLE
Make plugin start up shared server if it's not already running

### ISSUE THREAD

**Issue by JohnEricson** [vim-denops/denops.vim#281]
I noticed that Neovim gets slower on startup when this plugin is installed on Windows. On Linux it's fine. So for now I'm manually starting the shared server before I use Neovim which is a sub-optimal solution.
Is there a way to make the plugin discover if the server is running and if not, start it up before connecting? I'm fine if Neovim/Vim is a bit slower on the first start as long as it's faster after this. Just a thing that would make it more convenient to use.

**Comment by lambdalisue** [comment]
What you described doesn't match, but you might be satisfied with https://github.com/vim-denops/denops-shared-server.vim. Please check it out.

**Comment by JohnEricson** [comment]
This sounds like what I'm looking for. Thanks for pointing me in the right direction! 🙂
