### ISSUE TITLE
DenopsReady does not start

### ISSUE THREAD

**Issue by yasunori0418** [vim-denops/denops.vim#305]
## Environment

OS: Arch Linux
Neovim: HEAD

```
❯ nvim --version
NVIM v0.10.0-dev-2021+gee2127363
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

denops.vim version: 8b39cf7

```
❯ deno --version
deno 1.39.1 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3
```

## minimal configuraion

https://github.com/yasunori0418/denops_ready_test

```
let s:base_dir = '<sfile>'->expand()->fnamemodify(':p:h')
let s:denops = $'{s:base_dir}/plug/denops.vim'

exe 'set rtp^=' .. s:denops

autocmd User DenopsReady echomsg 'fired DenopsReady'
autocmd VimEnter * echomsg 'fired VimEnter'
```

## Occurring Issues

`DenopsReady` event does not start.

**Comment by Shougo** [comment]
I have checked the code.

```
      await host.call("execute", "doautocmd <nomodeline> User DenopsReady");
```

is executed.   But `User DenopsReady` is not fired.

`doautocmd User DenopsReady` works.

**Comment by Shougo** [comment]
Please test #306.

**Comment by yasunori0418** [comment]
I confirmed that DenopsReady works on the target branch.
Thank you for your response.
