### ISSUE TITLE
Difficult to get to API reference for denops_std

### ISSUE THREAD

**Issue by kyoh86** [vim-denops/denops.vim#329]
Thanks for always enjoying making plugins with denops.

The API for denops_std is documented in deno.land, but I still often get lost trying to reach it.

https://deno.land/x/denops_std@v6.4.0

I would like to suggest the following improvements.

- Put a link to the denops_std documentation in the denops.vim help documentation.
- Create a page in Denops Documents that introduces the standard library at the heading level, and link to the denops_std documentation from there.
- (This is not directly related to this issue, but since the standard theme of Denops Documents (`Light`) is almost indistinguishable from the links in the document, we would like to use a more distinguishable style (`Coal`) as the default.

I will submit a pull request for review.

**Comment by lambdalisue** [comment]
Close?

**Comment by kyoh86** [comment]
@lambdalisue yes, thank you!
