### ISSUE TITLE
Cloud not start denops process (Neovim: nightly/stable, Deno: 1.43.2, macOS: 14.4.1)

### ISSUE THREAD

**Issue by peacock0803sz** [vim-denops/denops.vim#341]
# Description

Deno start denops process (only for macOS?) since deno@1.43.2, but It **can do correctly with deno@1.43.1** (previous version).

# Environment Info

- macOS: `14.4.1` (arm64)
- deno: `1.43.2`
- Neovim: (It can reproduce both versions)
    - nightly (`NVIM v0.10.0-dev-3103+gca735c755`)
    - stable (`v0.9.5`)

# Expected behavior

Works with deno v1.43.2 (latest) in macOS

# Step to reproduce

Starting denops shared server with `deno run -A --no-lock path/to/vim-denops/denops.vim/denops/@denops-private/cli.ts --hostname=127.0.0.1 --port=32123`, and create `init.vim` as following.

```vim
set nocompatible
set runtimepath+=path/to/vim-denops/denops.vim

let g:denops#debug = v:true
let g:denops#trace = v:true
let g:denops_server_addr = '127.0.0.1:32123'
```

Then, start Neovim with the `init.vim` (`nvim -U NONE -u init.vim`), the deno process will crash with segmentation fault like bellow

```
$ deno run -A --no-lock ./denops/@denops-private/cli.ts --hostname=127.0.0.1 --port=32123
Listen denops clients on 127.0.0.1:32123
127.0.0.1:60178 is connected
zsh: segmentation fault  deno run -A --no-lock ./denops/@denops-private/cli.ts --hostname=127.0.0.1
```

The log message in Neovim (with `:messages`) as is:
```
[denops] Connecting to channel `127.0.0.1:32123` [1/4]
[denops] Channel connected (127.0.0.1:32123)
[denops] Channel closed (127.0.0.1:32123)
[denops] DenopsClosed
[denops] Channel closed. Reconnecting...
[denops] Connecting to channel `127.0.0.1:32123` [1/4]
[denops] Failed to connect channel `127.0.0.1:32123` [1/4]: Vim(let):接続に失敗しました: 接続
が拒否されました
[denops] Connecting to channel `127.0.0.1:32123` [2/4]
[denops] Failed to connect channel `127.0.0.1:32123` [2/4]: Vim(let):接続に失敗しました: 接続
が拒否されました
[denops] Connecting to channel `127.0.0.1:32123` [3/4]
[denops] Failed to connect channel `127.0.0.1:32123` [3/4]: Vim(let):接続に失敗しました: 接続
が拒否されました
[denops] Failed to connect channel `127.0.0.1:32123`: Vim(let):接続に失敗しました: 接続が拒否
されました
```

**Comment by Shougo** [comment]
Hm...  It works for me.

**Comment by peacock0803sz** [comment]
There was no problem with deno v1.43.1 or Linux, so it might deno problem....?

**Comment by ryota2357** [comment]
I have not faced this issue and also have not reproduced it with minimal init.vim

I'm using:
- macOS 14.4.1 (M1 Pro)
- deno v1.43.2 (installed via aqua)
- neovim HEAD (built with homebrew)

**Comment by peacock0803sz** [comment]
Exactly. I found the cause issue at denoland/deno 💯 
https://github.com/denoland/deno/issues/23766

**Comment by peacock0803sz** [comment]
It's not denops's problem, I'll close this issue 🙇 
Thank you to @mopp @ryota2357 for checking/sharing conditions :)
