### ISSUE TITLE
[denops]     at file:///home/user/.vim/plugged/ddc.vim/denops/ddc/deps.ts:19:15 ??

### ISSUE THREAD

**Issue by nemonein** [vim-denops/denops.vim#364]
I'm using vim 9.1(1-445), as well as neovim(v0.10.0) on Archlinux.
Deno's version is 1.43.6.

When I run vim/nvim, I got this message.
```
[denops]     at file:///home/user/.vim/plugged/ddc.vim/denops/ddc/deps.ts:19:15
```

What does this mean?
I'm using `vim-plug` and all plugins are up-to-date.

**Comment by Milly** [comment]
@nemonein 
The message is multi-line. Please paste the output of the `:messages` command.

**Comment by nemonein** [comment]
Thank you for your answer.
Here's the whole messages.

```
[denops] ********************************************************************************
[denops] Deno module cache issue is detected.
[denops] Execute 'call denops#cache#update(#{reload: v:true})' and restart Vim/Neovim.
[denops] See https://github.com/vim-denops/denops.vim/issues/358 for more detail.
[denops] ********************************************************************************
[denops] Failed to load plugin 'ddc': TypeError: Could not find constraint in the list of versions: @std/encoding@0.224.3
[denops]   Specifier: jsr:@std/encoding@0.224.3/base64
[denops]     at file:///home/user/.local/share/nvim/plugged/ddc.vim/denops/ddc/deps.ts:19:15
```

I tried `call denops#cache#update(#{reload: v:true})` and restarted `nvim`, but the result is the same.

**Comment by Shougo** [comment]
Because current `denops#cache#update()` does not support `ddc.vim`. 

Please see this.

https://github.com/vim-denops/denops.vim/issues/360
