### ISSUE TITLE
`g:denops#server#deno` is not available

### ISSUE THREAD

**Issue by Milly** [vim-denops/denops.vim#369]
### Describe the bug

Doc says about `g:denops#server#deno`:

https://github.com/vim-denops/denops.vim/blob/c6fa7c615ea7209ece65b2322591f0dd0167358d/doc/denops.txt#L109-L111

But it is not implemented.

### Your environment

- Denops version: v6.0.8 c6fa7c615ea7209ece65b2322591f0dd0167358d

**Comment by lambdalisue** [comment]
Let's assume it is just documentation issue and remove that entry from doc
