### ISSUE TITLE
denops can't detect latest version of Deno

### ISSUE THREAD

**Issue by giginet** [vim-denops/denops.vim#400]
### Describe the bug

I'm using Deno 1.45.5, however, denops raises 'Unsupported Deno version' error.

This is the output of `:checkhealth`

```
denops: health#denops#check

- Supported Deno version: `1.45.0`
- Supported Vim version: `9.1.0448`
- Supported Neovim version: `0.10.0`
- Detected Deno version: `1.39.4`
- ERROR Unsupported Deno version is detected. You need to upgrade it to `1.45.0` or later.
- Detected Neovim version: `0.10.1`
- OK Neovim version check: passed
- Denops status: `stopped`
- ERROR Denops is stopped. Execute `:message` command to find reasons.
```

I'm using Deno 1.45.5, Neovim 0.10.1 and denops 7.0.2. This issue is not reproduced with denops 6.0.11

### Provide a minimal vimrc with less than 50 lines to reproduce

```vim
```

### Expected behavior

The latest version should be detected as the supported versions.

### Your environment

- OS: `Darwin`
- Deno version: `deno --version` 1.45.5
- Vim/Neovim version: `vim --version` or `nvim --version` 0.10.1
- Denops version: `git log -1` (run in the denops.vim repository) 7.0.2

**Comment by lambdalisue** [comment]
Hum... It seems the deno binary visible from your vim is invalid. Please confirm the value of `echo exepath('deno')` is correct (and set `g:denops#deno` to the correct path if it's invalid)

https://github.com/vim-denops/denops.vim?tab=readme-ov-file#for-users

**Comment by giginet** [comment]
This is the full output of `deno --version` in my env.

```
deno 1.45.5 (release, aarch64-apple-darwin)
v8 12.7.224.13
typescript 5.5.2
```

**Comment by giginet** [comment]
Oops, I called `echo exepath('deno')` then it specified another deno executable. This issue was caused by my setup.
Thank you!
