### ISSUE TITLE
Could not connect servers on launch time with denops 7.x

### ISSUE THREAD

**Issue by giginet** [vim-denops/denops.vim#401]
### Describe the bug

Using denops 7.0.x, denops attempts to connect to the server several times on the editor startup, but it seems to be failed due to the following errors.

```
[denops] Server stopped (1). Restarting...
[denops] Failed to connect channel ``: Vim(let):connection failed: tcp address must be host:port
[denops] error: Could not find constraint in the list of versions: @std/async@^1.0.1
[denops]   Specifier: jsr:@std/async@^1.0.1/deadline
[denops]     at file:///Users/giginet/.local/share/nvim/lazy/denops.vim/denops/@denops-private/cli.ts:5
:26
```

As I tried, this error is not reproduced using denops 6.0.11.

### Provide a minimal vimrc with less than 50 lines to reproduce

Just install denops with lazy.nvim without any settings.

### How to reproduce the problem from Vim startup

Start Neovim

### Expected behavior

Any errors are not occur

### Actual behavior

Failed to connect to the server

### Your environment

- OS: `uname -a` (macOS/Linux) or `ver` (Windows) Darwin
- Deno version: `deno --version`  1.45.5
- Vim/Neovim version: `vim --version` or `nvim --version` Neovim 0.10.1
- Denops version: `git log -1` (run in the denops.vim repository) 7.0.2

**Comment by lambdalisue** [comment]
Could you try `call denops#cache#update(#{reload: v:true})`?

https://github.com/vim-denops/denops.vim/blob/fcc579be1f11d24b56d4d0180bd6ca8a8b919cdb/doc/denops.txt#L252-L260

**Comment by giginet** [comment]
This suggestion seems to be working fine 🎉 
Thank you!

**Comment by Shougo** [comment]
Hm...  I think the error check is needed for it.

Current implementation just checks for external denops modules.
