### ISSUE TITLE
SVG Icons

### ISSUE THREAD

**Issue by Milly** [vim-denops/denops.vim#408]
Black + White background
[![denops-bg](https://github.com/user-attachments/assets/9626f149-4ce9-4c78-a73e-3e08356c977f)](https://github.com/user-attachments/assets/9626f149-4ce9-4c78-a73e-3e08356c977f)
Black + Transparent
[![denops-black](https://github.com/user-attachments/assets/4e223935-b4aa-469e-a498-10f59686c766)](https://github.com/user-attachments/assets/4e223935-b4aa-469e-a498-10f59686c766)
White + Transparent
[![denops-white](https://github.com/user-attachments/assets/9ef29032-f240-4a1a-a0c8-872b912f9ef4)](https://github.com/user-attachments/assets/9ef29032-f240-4a1a-a0c8-872b912f9ef4)
Image shield
[![Denops.vim 7.0.0 or above](https://img.shields.io/badge/Denops.vim-Support%207.0.0-yellowgreen.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEiIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIj48cGF0aCBkPSJNIDQ4MS45NTMgMjA5LjUxNyBDIDQ4Ny4xMjcgMjQ3LjU3NiAzNTcuMTcxIDQ4NC44NjQgMzA4Ljg5MiA0NzguOTg2IEMgMjg4LjcwOSA0NzYuNTI4IDIzNS45NDkgNDUyLjEyMSAxNzQuMDkzIDQxNS44MzQgQyAxNjQuMzEzIDQyNi4yMzkgMTIzLjAwNSA0NTYuODEgMTA2LjgzMiA0NTAuNTAzIEMgNzUuOTAxIDQzOC40NDMgNTkuMTYyIDMzOC4xNDEgNjAuMzY4IDM0My4yMjYgQyAzNy4xMTIgMzI0LjUxIDIxLjUzOSAzMDcuOTg0IDE5Ljk2NyAyOTcuMDcxIEMgMTguMzE1IDI4NS41ODcgMjYuMTIxIDI2Mi4zOTMgMzkuMzEzIDIzNC4xNiBDIDI3LjMyNSAxNTcuNTggMjEuNTczIDg1Ljk1NiAyOC43NjYgNzYuMjkxIEMgMzYuNzkxIDY1LjUwNSA5Ni4wMTIgNjEuMjMxIDEwMC44MjYgNjQuNjI5IEMgMTAzLjU5MiA2Ni41NzkgMTA3LjQ0MyA4NC4xMjEgMTExLjY3NyAxMDkuMzM0IEMgMTQyLjc4NCA2My43MzcgMTc4LjMyNSAyNC44MDIgMTk0LjI5IDIxLjYzNiBDIDIwOC42NTUgMTguNzg5IDMwNS4xNzUgNjcuMDQ3IDMwNi45NyA2Ny44NTggQyAzMTQuNTU0IDU4LjgyNiAzMjMuNTI0IDQ1LjcyIDMyNi4yMjQgNDQuNzQ1IEMgMzM0LjU0NSA0MS43NCAzOTkuMDE3IDU3LjA4OSA0MDQuNDkgNjcuNjc2IEMgNDEwLjIzNyA3OC43ODcgMzkxLjg2MiAxMTUuMTMxIDM4Ny41MzUgMTIyLjczNyBDIDQ0MS43MDEgMTU4LjQwNSA0NzguOTExIDE4Ny4xNDIgNDgxLjk1MyAyMDkuNTE3IFogTSAxODguNTYzIDM2MS4wNjMgQyAxNzQuOTcgMzU2LjAxNiAxNTUuMDQzIDMzNi42ODEgMTQ4LjUxOSAzMjMuNTE5IEMgMTM5LjAxMSAzMzcuNDAxIDEzMi4zMTkgMzQ3LjMxNiAxMzIuMzE5IDM0Ny4zMTYgQyAxMzIuMzE5IDM0Ny4zMTYgOTIuODE3IDg5LjAxNiA4Ny42ODggODUuMzk1IEMgODUuMzAzIDgzLjcxMSA1NC44NTYgODQuMTUgNDkuMzMxIDkxLjU3NCBDIDQzLjkyMSA5OC44NDYgNzguMDYxIDQwMC41NjQgMTE1LjM0NSA0MjAuMzY4IEMgMTMxLjY2MyA0MjkuMDM1IDE3Ny43MzkgMzc0LjYxNSAxODguNTYzIDM2MS4wNjMgWiBNIDI3NS40NTUgMTM5LjM4NSBDIDI4Ny40OTYgMTM4LjU1NCAyOTkuMDM4IDEzOS42MzQgMzExLjQxOCAxNDIuNTA4IEMgMzExLjMwOSAxMzguNjgyIDMxMS42MTYgMTM1LjQxOCAzMDcuNzEyIDEzMS43NjMgQyAzMDEuNjU0IDEzMy41MTggMjkyLjA0OCAxMzUuODM1IDI4My4zMTEgMTMyLjA5IEMgMjgxLjg5MyAxMzMuNzQgMjc3Ljc4IDEzOS4xIDI3NS40NTUgMTM5LjM4NSBaIE0gMzI3LjI4NSA3Ni41NDcgQyAzMzguODU5IDgzLjIxMSAzNTkuNTg3IDk3LjIwOCAzNjQuMDA5IDExMi41OTMgQyAzNzUuNjIgOTcuNzI2IDM4MS40MTQgODMuNTcgMzc5Ljg1NCA3OC4yNzMgQyAzNzUuNjk4IDcxLjc5MSAzNDMuNzg1IDY0LjU4MyAzMzYuOTgxIDY3LjM5MyBDIDMzNC43MDggNjguMzMgMzI5LjU0NiA3My4zMTggMzI3LjI4NSA3Ni41NDcgWiBNIDMxMy43MDYgMTA5LjQzMSBDIDMyNi44MTIgMTI2LjM2OCAzMzQuNTM1IDE1OS44MTkgMzM1LjExIDE2OS42MDYgQyAzMjUuNDk5IDE2NC43NiAyNzIuNzQ4IDE1NS45NDQgMjUwLjcwOCAxNjIuMDM1IEMgMjQxLjI0NCAxMTEuOTE4IDIxNC40OTMgODUuNTM5IDE5OC42MTQgODMuNTEgQyAxODIuNjkxIDgxLjQ3NyAxNjcuODcgODkuMjE0IDE2NC4xNDMgMTAwLjA1NSBDIDE2MC40MTYgMTEwLjg5NiAxNjguNDA1IDEyNC4zMzkgMTgzLjMxMiAxMjUuNjkzIEMgMTk4LjIxOSAxMjcuMDQ4IDIwOS41NzIgMTE3LjkzMSAyMDkuNTcyIDExNy45MzEgQyAyMDkuNTcyIDExNy45MzEgMjI5LjQ2NyAxNDYuMjkxIDIyOC4xNTkgMTY2LjMxMyBDIDE5Mi4zODQgMTc1LjcwMSAxNTMuMjE5IDIxNy40MDcgMTUzLjIxOSAyNjAuMDExIEMgMTUzLjIxOSAzMTMuODE4IDIwNi4yNjUgMzU3Ljc2MSAyNzIuOTg3IDM2MC40OTEgQyAyNzEuNTEyIDM4NS4yOTYgMjcwLjIxIDQyMi40NjYgMzEwLjIwMyA0NDguNSBDIDMzMi4wODggNDM4LjY2NyAzOTUuMDk5IDM0OS43OTggNDA3LjgwMyAzMjMuMTE5IEMgNDAxLjc1OSAzMTYuMDI0IDM5Ni43ODEgMzEzLjcyOSAzODguNzcxIDMxMC42ODIgQyAzOTkuNjg3IDI5NS44IDQwNS45NDIgMjc4LjQ4OCA0MDUuOTQyIDI2MC4wMTEgQyA0MDUuOTQyIDIyNS4zMDYgMzg5LjE2MSAxOTUuNjM3IDM1NS41ODggMTc3LjU1MSBDIDM1Ny4yMzYgMTM4LjI3MiAzMzEuNzU0IDg5LjAzOSAzMDcuNTg0IDgyLjM1OCBDIDI5Mi4xMTEgNzguMDgxIDI3Ny40NTggODMuMDA4IDI3My43MzEgOTMuODQ4IEMgMjcwLjAwMiAxMDQuNjg4IDI3OC4yMDIgMTEzLjc0MSAyODkuMzE0IDExNi43MTYgQyAzMDAuOTM4IDExOS44MyAzMDcuNDg2IDExNC40NyAzMTMuNzA2IDEwOS40MzEgWiBNIDI3NS4xNzcgMjI1LjYyNSBDIDI3NS4xNzcgMjMxLjcwNyAyNzAuMjQ3IDIzNi42MzcgMjY0LjE2NiAyMzYuNjM3IEMgMjU4LjA4NSAyMzYuNjM3IDI1My4xNTUgMjMxLjcwNyAyNTMuMTU1IDIyNS42MjUgQyAyNTMuMTU1IDIxOS41NDUgMjU4LjA4NSAyMTQuNjE1IDI2NC4xNjYgMjE0LjYxNSBDIDI3MC4yNDcgMjE0LjYxNSAyNzUuMTc3IDIxOS41NDUgMjc1LjE3NyAyMjUuNjI1IFogTSAyMjguMDg4IDIyNy40ODggQyAyMjguMDg4IDIzMy42NjQgMjIzLjA4MyAyMzguNjY4IDIxNi45MDggMjM4LjY2OCBDIDIxMC43MzQgMjM4LjY2OCAyMDUuNzI5IDIzMy42NjQgMjA1LjcyOSAyMjcuNDg4IEMgMjA1LjcyOSAyMjEuMzEzIDIxMC43MzQgMjE2LjMwOSAyMTYuOTA4IDIxNi4zMDkgQyAyMjMuMDgzIDIxNi4zMDkgMjI4LjA4OCAyMjEuMzEzIDIyOC4wODggMjI3LjQ4OCBaIiBmaWxsPSIjZmZmIi8+PC9zdmc+Cg==)](https://github.com/vim-denops/denops.vim/releases/tag/v7.0.0)

**Comment by Milly** [comment]
Later PR to https://github.com/vim-denops/denops-logos

**Comment by Milly** [comment]
@hashrock
I made these denops.vim logo icons. I used your image as a reference for the ant design. Can I make a PR for these images to https://github.com/vim-denops/denops-logos? Do you have any thoughts on the license?

**Comment by hashrock** [comment]
Great!
How about using `CC BY-NC-ND 4.0` to align other assets?
